Repository boostcampwm-2021/Android08-Ratatouille, pull requests merged in 2021-12, with the labels that each got.

#252 [develop] localdatasource 리뷰반영
  local/src/test/java/com/kdjj/local/dataSource/RecipeImageLocalDataSourceImplTest.kt
  local/src/test/java/com/kdjj/local/dataSource/RecipeListLocalDataSourceImplTest.kt
  local/src/test/java/com/kdjj/local/dataSource/RecipeLocalDataSourceImplTest.kt
Labels: refactor

#265 [develop] notification 수정
  presentation/src/main/java/com/kdjj/presentation/services/TimerService.kt
  presentation/src/main/java/com/kdjj/presentation/view/recipedetail/RecipeDetailActivity.kt
Labels: refactor

#270 [develop] 힐끔보기에서 네트워크 연결이 안되어 있을 시 개요 이동시에 무한로딩 발생 #269
  presentation/src/main/java/com/kdjj/presentation/viewmodel/recipesummary/RecipeSummaryViewModel.kt
Labels: bug

#271 [develop] 타이머 configuration change 대응 #266
  presentation/src/main/java/com/kdjj/presentation/view/recipedetail/RecipeDetailActivity.kt
  presentation/src/main/java/com/kdjj/presentation/viewmodel/recipedetail/RecipeDetailViewModel.kt
Labels: bug, refactor

#274 [develop] README 내용 수정
  README.md
Labels: feature
