Repository boostcampwm-2021/Android08-Ratatouille, pull requests merged in 2021-11, with the labels that each got.

#10 [develop] Recipe 필요 프로퍼티 추가
  domain/src/main/java/com/kdjj/domain/model/Recipe.kt
  domain/src/main/java/com/kdjj/domain/model/RecipeStep.kt
Labels: feature

#26 [develop] Hilt에서 List 사용 시 발생하는 에러 해결
  app/src/main/java/com/kdjj/ratatouille/di/RepositoryModule.kt
  app/src/main/java/com/kdjj/ratatouille/di/presentation/FakeModule.kt
  domain/src/main/java/com/kdjj/domain/usecase/FetchRecipeTypesUseCase.kt
Labels: bug, hilt

#34 [develop] 도메인 Recipe 모델 수정
  domain/src/main/java/com/kdjj/domain/model/Recipe.kt
  domain/src/main/java/com/kdjj/domain/model/RecipeState.kt
  local/src/main/java/com/kdjj/local/Mapper.kt
  presentation/src/main/java/com/kdjj/presentation/common/IdGenerator.kt
  presentation/src/main/java/com/kdjj/presentation/common/RecipeMapper.kt
  presentation/src/main/java/com/kdjj/presentation/common/Utils.kt
  presentation/src/main/java/com/kdjj/presentation/model/RecipeItem.kt
  presentation/src/main/java/com/kdjj/presentation/viewmodel/recipeeditor/RecipeEditorViewModel.kt
Labels: feature

#75 [develop] SaveRecipeUseCase 레시피 이미지 저장하는 로직 추가 #73
  domain/src/main/java/com/kdjj/domain/usecase/SaveRecipeUseCase.kt
Labels: feature

#125 [develop] UploadRecipeUseCase 수정
  domain/src/main/java/com/kdjj/domain/usecase/UploadRecipeUseCase.kt
Labels: refactor

#163 [develop] spancount에 따른 View 크기 동적 지정 및 View간의 간격 유지
  presentation/src/main/java/com/kdjj/presentation/view/home/my/MyRecipeFragment.kt
  presentation/src/main/java/com/kdjj/presentation/view/home/my/SpacesItemDecoration.kt
  presentation/src/main/res/layout/fragment_my_recipe.xml
  presentation/src/main/res/layout/item_my_recipe.xml
  presentation/src/main/res/layout/item_my_recipe_add_recipe.xml
  presentation/src/main/res/layout/item_my_recipe_progress.xml
  presentation/src/main/res/values/dimens.xml
Labels: refactor

#169 fix: 개요 들어올 시 타입 업데이트 하는 기능 추가 close #135
  presentation/src/main/java/com/kdjj/presentation/viewmodel/recipesummary/RecipeSummaryViewModel.kt
Labels: fix

#187 [develop] 버전 업데이트
  app/build.gradle
Labels: feature

#204 [develop] Splash화면 이미지 크기 수정
  presentation/src/main/res/layout/activity_splash.xml
  presentation/src/main/res/values/dimens.xml
Labels: refactor

#210 [develop] 레시피 삭제 전에 유저에게 한번 더 묻는 창 보여주는 기능 구현 #209
  presentation/src/main/java/com/kdjj/presentation/view/recipesummary/RecipeSummaryActivity.kt
  presentation/src/main/java/com/kdjj/presentation/viewmodel/recipesummary/RecipeSummaryViewModel.kt
  presentation/src/main/res/layout/activity_recipe_summary.xml
Labels: feature

#213 [develop] 레시피 개요 이미지 코너 둥글게 구현 #212
  presentation/src/main/res/layout/activity_recipe_summary.xml
  presentation/src/main/res/values/dimens.xml
Labels: design

#217 [develop] 레시피 로딩전에 항목 보이지 않도록 수정 #214
  presentation/src/main/res/layout/activity_recipe_summary.xml
Labels: fix, design

#221 [develop] 내 레시피 화면 progress바 수정
  presentation/src/main/java/com/kdjj/presentation/viewmodel/my/MyRecipeViewModel.kt
Labels: fix

#230 [develop] 검색 결과 없음 표시
  presentation/src/main/java/com/kdjj/presentation/viewmodel/search/SearchViewModel.kt
  presentation/src/main/res/layout/fragment_search_recipe.xml
  presentation/src/main/res/values/dimens.xml
  presentation/src/main/res/values/strings.xml
Labels: feature
